package com.networkedassets.git4c.core.business

import com.networkedassets.git4c.core.datastore.extractors.LineNumbersExtractorData

interface LinesExtractionHandler: ExtractionHandler<LineNumbersExtractorData>