package com.networkedassets.git4c.infrastructure

import com.atlassian.cache.CacheFactory
import com.networkedassets.git4c.core.datastore.EncryptedMacroSettingsCache
import com.networkedassets.git4c.data.macro.EncryptedDocumentationsMacroSettings


class AtlassianEncryptedMacroSettingsCache(cacheFactory: CacheFactory): ConfluenceCache<EncryptedDocumentationsMacroSettings>(cacheFactory), EncryptedMacroSettingsCache
