package com.networkedassets.git4c.infrastructure.plugin.converter.markdown

import com.networkedassets.git4c.core.business.Macro
import net.sourceforge.plantuml.FileFormat
import net.sourceforge.plantuml.FileFormatOption
import net.sourceforge.plantuml.SourceFileReader
import spock.lang.Specification

import java.nio.file.Files
import java.nio.file.Paths

import static com.networkedassets.git4c.infrastructure.plugin.converter.ConverterUtils.getConvertedMarkdown

class PumlTest extends Specification {

    def "UML should be converted and added to markdown in Multi File Macro"() {

        given:
        def puml = Paths.get("src/test/resources", "markdown/pumlTest/umls/test.puml")
        def tempDirectory = Files.createTempDirectory("temp").toFile()
        def webPage = getConvertedMarkdown("pumlTest", Macro.MacroType.MULTIFILE).content

        when:
        def reader = new SourceFileReader(puml.toFile(), tempDirectory, new FileFormatOption(FileFormat.SVG))
        def image = reader.generatedImages[0].pngFile

        def base64 = Files.readAllBytes(image.toPath()).encodeBase64()
        def xml = new XmlSlurper().parseText(webPage)
        def img = xml.p.img

        then:
        //To check if file was successfully converted
        base64.toString().size() > 20
        //SVG have autogenerated ids inside and we can't just compare two svgs
        img.@src.toString().startsWith("data:image/svg+xml;base64")
        tempDirectory.deleteDir()
    }

    def "Empty PUML shouldn't be converted and added to markdown in Multi File Macro"() {

        given:
        def tempDirectory = Files.createTempDirectory("temp").toFile()
        def webPage = getConvertedMarkdown("emptyPumlTest", Macro.MacroType.MULTIFILE).content

        when:
        def xml = new XmlSlurper().parseText(webPage)
        def img = xml.p.img

        then:
        img.isEmpty()
        tempDirectory.deleteDir()
    }

    def "UML should be converted and added to markdown in Single File Macro"() {

        given:
        def puml = Paths.get("src/test/resources", "markdown/pumlTest/umls/test.puml")
        def tempDirectory = Files.createTempDirectory("temp").toFile()
        def webPage = getConvertedMarkdown("pumlTest", Macro.MacroType.SINGLEFILE).content

        when:
        def reader = new SourceFileReader(puml.toFile(), tempDirectory, new FileFormatOption(FileFormat.SVG))
        def image = reader.generatedImages[0].pngFile

        def base64 = Files.readAllBytes(image.toPath()).encodeBase64()
        def xml = new XmlSlurper().parseText(webPage)
        def img = xml.p.img

        then:
        //To check if file was successfully converted
        base64.toString().size() > 20
        //SVG have autogenerated ids inside and we can't just compare two svgs
        img.@src.toString().startsWith("data:image/svg+xml;base64")
        tempDirectory.deleteDir()
    }

    def "Empty PUML shouldn't be converted and added to markdown in Single File Macro"() {

        given:
        def tempDirectory = Files.createTempDirectory("temp").toFile()
        def webPage = getConvertedMarkdown("emptyPumlTest", Macro.MacroType.SINGLEFILE).content

        when:
        def xml = new XmlSlurper().parseText(webPage)
        def img = xml.p.img

        then:
        img.isEmpty()
        tempDirectory.deleteDir()
    }
}
