package com.networkedassets.git4c.infrastructure.plugin.converter.puml

import net.sourceforge.plantuml.FileFormat
import net.sourceforge.plantuml.FileFormatOption
import net.sourceforge.plantuml.SourceFileReader
import spock.lang.Specification

import java.nio.file.Files
import java.nio.file.Paths

import static com.networkedassets.git4c.infrastructure.plugin.converter.ConverterUtils.getPUML

class ConversionTest extends Specification {

    def "Non empty UML should be converted and added to img tag"() {

        given:
        def puml = Paths.get("src/test/resources", "markdown/pumlTest/umls/test.puml")
        def tempDirectory = Files.createTempDirectory("temp").toFile()

        when:
        def reader = new SourceFileReader(puml.toFile(), tempDirectory, new FileFormatOption(FileFormat.SVG))
        def image = reader.generatedImages[0].pngFile
        def convertedAsciiDoc = getPUML(puml.toFile().parentFile.getAbsolutePath())
        def base64 = Files.readAllBytes(image.toPath()).encodeBase64()
        def xml = new XmlSlurper().parseText(convertedAsciiDoc.content)
        def img = xml.img

        then:
        //To check if file was successfully converted
        base64.toString().size() > 20
        //SVG have autogenerated ids inside and we can't just compare two svgs
        img.@src.toString().startsWith("data:image/svg+xml;base64")

    }

    def "Empty UML should return empty content"() {

        given:
        def puml = Paths.get("src/test/resources", "markdown/emptyPumlTest/umls/test.puml")

        when:
        def convertedAsciiDoc = getPUML(puml.toFile().parentFile.getAbsolutePath())

        then:
        convertedAsciiDoc.content == "<div></div>"

    }

}
